export const metadata = {
	title: "AKJ.IO",
	description: "Generated by Next.js",
};

import styles from "../styles/Home.module.scss";

import "../styles/global-styles.scss";

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				{children}

				<footer className={styles.footer}>
					Copyright 2023 - Allan Kimmer Jensen
				</footer>
			</body>
		</html>
	);
}
